# Generated by Django 6.0.1 on 2026-01-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Назва')),
                ('fund_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер фонду')),
                ('category', models.CharField(blank=True, max_length=150, null=True, verbose_name='Категорія')),
                ('creation_date', models.DateField(blank=True, null=True, verbose_name='Дата створення')),
                ('archivist_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Архіваріус')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
            ],
        ),
    ]
